"""Add winner field to Auction

Revision ID: 59c7539e24f1
Revises: 82d4eff948cb
Create Date: 2025-02-07 03:12:51.793630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c7539e24f1'
down_revision = '82d4eff948cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
